name: "Build XLCore"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/XIVLauncher.Core/
    concurrency:
      group: ${{ github.head_ref }}"
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x

      - name: Dotnet Restore
        run: dotnet restore

      - name: Dotnet Build (Default)
        run: dotnet publish -r linux-x64 --sc -o --configuration Release --no-restore -o ./dist/XIVLauncher.Core

      - name: Dotnet Build (Arch)
        run: dotnet publish -r linux-x64 --sc -o --configuration Release -p:DefineConstants=WINE_XIV_ARCH_LINUX --no-restore -o ./dist/XIVLauncher.Core-arch

      - name: Dotnet Build (Fedora)
        run: dotnet publish -r linux-x64 --sc -o --configuration Release -p:DefineConstants=WINE_XIV_FEDORA_LINUX --no-restore -o ./dist/XIVLauncher.Core-fedora

      - name: Dotnet Test
        run: dotnet test --no-build --verbosity normal